#####################################
########   Cookien Consent   ########
#####################################

cookie-consent-message: "Diese Website nutzt Cookies, um dich so richtig zu verwöhnen."
cookie-consent-dismiss-button-text: "Alles klar!"
cookie-consent-more-info-message: "Mehr erfahren"
cookie-consent-more-info-url: "https://www.google.com/intl/de/policies/privacy/partners/"

#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################

# This is your site title
title: CoderDojo Wien
# Website language
lang: de-AT
# Header Title
header-title:
# Header Tagline
headter-tagline:
# Description
description: Das CoderDojo ist ein Club für Kinder und Jugendliche zwischen 8 und 17 Jahren, in dem sie Technik und Programmieren lernen können.
# Keywords
keywords: "Kinder Lernen Programmieren Technik Dojo Wien Mentoring CoderDojo"

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Termine
  url: '/#events'

# Secondary Buttons
header-secondary-button:
  title: Kontakt
  url: '/#contact'

#
# If your website is placed in a separate folder on your server please modify
# this with your folder name, by default is empty.
# Example: Sera Demo is hosted on projects.gleesik.ro/sera-onepage
# If I compile Sera Template and I put in /sera-onepage without modifing baseurl
# than scripts can't be loaded corectly.
# For this example my site url is: projects.gleesik.ro (This can be just www.example.com)
# My folder for Demo Website is: /sera-onepage so baseurl: /sera-onepage
#
baseurl:

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: hallo@wien.coderdojo.net

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: '/#contact'

####################################
######  Global Social Links   ######
####################################
youtube: 'https://www.youtube.com/channel/UCsNUvEMrAXmWUicpXJXHKQw'
pinterest:
facebook: 'https://www.facebook.com/coderdojowien'
twitter: 'https://twitter.com/coderdojowien'
google-plus: 'https://plus.google.com/b/117361304524937577544/117361304524937577544/'
vimeo:
linkedin: 'https://www.linkedin.com/company/coderdojowien'

# Google Map JS api
# This is my api for this template
key-api: AIzaSyA3sRKRuJN5RybRwAc79U3wBn6S8SEfVU4
map-text: CoderDojo Wien
map-text-location: Vienna, Austria
map-lat: 48.2108226
map-lng: 16.3675638

#####################################
#############   About   #############
#####################################
about-title: CoderDojo Wien
about-description: "<p>
Das CoderDojo ist ein Club für Kinder und Jugendliche zwischen 8 und 17 Jahren, in dem sie Technik und Programmieren lernen können. In regelmäßigen Treffen werden verschiedene Übungen gemacht.
</p>
<h2>Warum</h2>
<p>
Wir glauben das unsere Kinder und Jugendliche der Schlüssel sind um die gesellschaftlichen Probleme der Zukunft zu lösen. Deswegen haben wir uns entschlossen den Kindern und Jugendlichen einem Raum zu geben in dem sie sich in einem sozialen Umfeld auf eine informelle, kreative Art und Weise weiterbilden können. Ein Raum in dem die Erforschung von Technologie Freude macht.
</p>
<h2>Für wen</h2>
<p>
Wenn du zwischen 8 und 17 Jahre alt bist, komm vorbei. Alles was du machen musst, ist sich <a href=\"#events\">für einen Termin anzumelden.</a>
<b>Wenn du jünger als 13 Jahre bist, muss dich ein Erwachsener begleiten und ganze Zeit anwesend sein.</b>
</p>
<h2>Wie viel kostet es</h2>
<p>
Unsere CoderDojo ist für die Kinder <b>kostenlos</b>. CoderDojo Wien ist ein Teil weltweiten <a target=\"_blank\" href=\"https://coderdojo.com/\">CoderDojo Bewegung</a> der ausschauschließlich ehrenamtlich basierend ist.
</p>
<h2>Wie läuft ein CoderDojo ab</h2>
<p>
Dōjō [doːdʑoː] kommt aus japanischen und steht für einen Trainingsraum für verschiedene Kampfkünste. Wir werden gemeinsam jedoch keine Kampfkünste sondern Programmieren trainieren. 
Wir haben einige Beispiele vorbereitet, jedoch stehen deine Ideen im Mittelpunkt. Wenn du ein cooles Projekt hast, bring es mit. Im CoderDojo 
hast du Hilfe von <a href=\"#team\">Mentoren</a>, die viel Erfahrung und Wissen haben. Ein Mentor begleitet dich bei den ersten Schritten aber auch wenn du 
schon erfahrener bist und eigene Projekte umsetzen möchtest.
</p>"

#####################################
############  Exercises  ############
#####################################
exercises-title: Übungen
exercises-description:

#####################################
############### Team ################
#####################################
team-title: Unser Team
team-description: "<p>
Wir sind ehrenamtlich engagierte Fachexperten. Wir kommen um dich zu unterstützen und in dir das Potenzial zu entfalten. 
Aber wir lernen und hören auch gerne zu. Wir sind keine Lehrer, sondern Menschen die Spaß daran haben mit Kindern zu arbeiten.
</p>
<h2>Mentor werden</h2>
<p>
Möchtest du selber ein Mentor werden? Fülle unsere <a href=\"https://de.surveymonkey.com/r/GBNGGFP\">Umfrage</a> aus oder <a href=\"#contact\">schreib uns.</a>
</p>"

# Members in separate data file

#####################################
############## Events ###############
#####################################
events-title: Termine
events-description: "<p>
<b>Für ein CoderDojo brauchst du grundsätzlich einen Laptop</b> ein Tablet oder Smartphone reicht nicht aus.
</p>
<h2>Was du vorbereitet kannst</h2>
<p>
<b>Es gibt ein paar Vorbereitungsschritte die du zu hause machen kannst um das Zeit bei CoderDojo zu sparen.</b> 
Falls du hilfe brauchst frage deine Eltern, wir helfen dir in zweifellsfall gern auch vor ort. Wir verwenden verschiede Sprachen und Technologien um das Programmieren zu lernen. 
Für die kleinsten und Anfänger nutzen wir vor allem <a target=\"_blank\" href=\"https://scratch.mit.edu/\">Scratch</a>.
</p>
<h3>Vorbereitung für Scratch</h3>
<p>
Installiere dir einen <a target=\"_blank\" href=\"https://scratch.mit.edu/download\">Scratch</a> Client.
</p>
<h3>Vorbereitung für C#</h3>
<p>
Für C# brauchst du entweder <a target=\"_blank\" href=\"https://www.visualstudio.com/downloads/\">Visual Studio Community 2017</a> oder <a target=\"_blank\" href=\"https://code.visualstudio.com/\">Visual Studio Code</a> zu installieren.
</p>"

#####################################
############   Contact   ############
#####################################
contact-title: Sag Hallo
contact-description: "<p>Hast du Fragen? Schreib uns hier oder sag einfach <a href=\"mailto:hallo@wien.coderdojo.net\">Hallo</a></p>!"

#####################################
#############   Footer   ############
#####################################
footer-description:
footer-copyright-text: CoderDojo Wien
footer-copyright-url:
footer-copyright-year: 2017
footer-imprint-text: Impressum und Datenschutz
footer-imprint-url: /impressum

#####################################
############# Components ############
#####################################
plugins_dir:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-assets
  - jekyll-last-modified-at

sass:
  sass_dir: _scss
  style: compressed

# Information for compile
exclude: [".gitignore", "node_modules", "docker-compose.yml", "Gemfile", "Gemfile.lock", "gulpfile.js", "package.json", "README.md"]