#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################

# This is your site title
title: "CoderDojo Wien"
# Website language
lang: "de-AT"
# Header Title
header-title:
# Header Tagline
headter-tagline:
# Description
description: "Das CoderDojo ist ein Club für Kinder und Jugendliche zwischen 8 und 17 Jahren, in dem sie Technik und Programmieren lernen können."
# Keywords
keywords: "Kinder, Programmieren, Programmierkurs, Programmierworkshop, Scratch, Technik, Wien, CoderDojo, Mentoring, Kinderkurs, Programmieren Lernen, Spielend Lernen, Spiele Programmieren, Arduino, Raspberry Pi, Microbit"

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Termine
  url: '/#events'

# Secondary Buttons
header-secondary-button:
  title: Kontakt
  url: '/#contact'

#
# If your website is placed in a separate folder on your server please modify
# this with your folder name, by default is empty.
# Example: Sera Demo is hosted on projects.gleesik.ro/sera-onepage
# If I compile Sera Template and I put in /sera-onepage without modifing baseurl
# than scripts can't be loaded corectly.
# For this example my site url is: projects.gleesik.ro (This can be just www.example.com)
# My folder for Demo Website is: /sera-onepage so baseurl: /sera-onepage
#
baseurl:

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: hallo@wien.coderdojo.net

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: '/donation'

# Google Map JS api
# This is my api for this template
key-api: AIzaSyA3sRKRuJN5RybRwAc79U3wBn6S8SEfVU4
map-text: CoderDojo Wien
map-text-location: Vienna, Austria
map-lat: 48.2108226
map-lng: 16.3675638

#####################################
############# Components ############
#####################################
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sass_dir: _scss
  style: compressed

# Information for compile
exclude: [".gitignore", "node_modules", "docker-compose.yml", "Gemfile", "Gemfile.lock", "gulpfile.js", "package.json", "README.md"]