#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: CoderDojo Wien
# Website language
lang: de-AT
# Header Title
header-title: <strong>bald</strong> da
# Header Tagline
headter-tagline: Wir sind

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Termine
  url: '#sponsorship'

# Secondary Buttons
header-secondary-button:
  title: Übungen
  url: '#exercises'

#
# If your website is placed in a separate folder on your server please modify
# this with your folder name, by default is empty.
# Example: Sera Demo is hosted on projects.gleesik.ro/sera-onepage
# If I compile Sera Template and I put in /sera-onepage without modifing baseurl
# than scripts can't be loaded corectly.
# For this example my site url is: projects.gleesik.ro (This can be just www.example.com)
# My folder for Demo Website is: /sera-onepage so baseurl: /sera-onepage
#
baseurl: 

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: hallo@wien.coderdojo.net

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: '#contact'

####################################
######  Global Social Links   ######
####################################
youtube: '#'
pinterest: '#'
facebook: 'https://www.facebook.com/coderdojowien'
twitter: 'https://twitter.com/coderdojowien'
google-plus: '#'
vimeo: '#'

# Google Map JS api
# This is my api for this template
key-api: AIzaSyA3sRKRuJN5RybRwAc79U3wBn6S8SEfVU4
map-text: CoderDojo Wien
map-text-location: Vienna, Austria
map-lat: 48.2108226
map-lng: 16.3675638

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: REPLACEME
  list-id: REPLACEME

#####################################
#############   About   #############
#####################################
about-title: CoderDojo Wien
about-description: Das CoderDojo ist ein Platz für Kinder und Jugendliche, die programmieren lernen und Spaß haben wollen. In regelmäßigen Treffen wird gelernt wie man Code schreibt, Webseiten entwickelt oder Apps und Spiele programmiert. <h3>Für wem?</h3>

#####################################
############  Exercises  ############
#####################################
exercises-title: Übungen
exercises-description: Maecenas tempus nec mi et placerat. Duis at odio vitae ex gravida volutpat. Nulla finibus aliquet diam ut eleifend. Mauris consequat interdum quam. Mauris dui sapien, efficitur et cursus id, molestie fringilla turpis.

#####################################
############### Team ################
#####################################
team-title: Unser Team
team-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

# Members in separate data file

#####################################
############## Events ###############
#####################################
events-title: Termine
events-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

#####################################
############   Contact   ############
#####################################
contact-title: Sag einfach Hallo!
contact-description: Hast du Fragen oder Anregungen? Schreib uns oder sag einfach <a href="mailto:hallo@wien.coderdojo.net">Hallo</a>!

#####################################
#############   Footer   ############
#####################################
footer-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat.
footer-copyright-text: CoderDojo Wien
footer-copyright-url: '#'
footer-copyright-year: 2017

#####################################
############# Components ############
#####################################
gems:
  - jekyll-sitemap

sass:
  sass_dir: _scss
  style: compressed

# Information for compile
exclude: [".gitignore", "node_modules", "docker-compose.yml", "Gemfile", "Gemfile.lock", "gulpfile.js", "package.json", "README.md"]