#####################################
########   Cookien Consent   ########
#####################################

cookie-consent-message: "Diese Website nutzt Cookies, um dich so richtig zu verwöhnen."
cookie-consent-dismiss-button-text: "Alles klar!"
cookie-consent-more-info-message: "Mehr erfahren"
cookie-consent-more-info-url: "https://www.google.com/intl/de/policies/privacy/partners/"

#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################

# This is your site title
title: CoderDojo Wien
# Website language
lang: de-AT
# Header Title
header-title:
# Header Tagline
headter-tagline:
# Description
description: Das CoderDojo ist ein Club für Kinder und Jugendliche zwischen 8 und 17 Jahren, in dem sie Technik und Programmieren lernen können.
# Keywords
keywords: "Kinder Lernen Programmieren Technik Dojo Wien Mentoring CoderDojo"

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Termine
  url: '/#events'

# Secondary Buttons
header-secondary-button:
  title: Kontakt
  url: '/#contact'

#
# If your website is placed in a separate folder on your server please modify
# this with your folder name, by default is empty.
# Example: Sera Demo is hosted on projects.gleesik.ro/sera-onepage
# If I compile Sera Template and I put in /sera-onepage without modifing baseurl
# than scripts can't be loaded corectly.
# For this example my site url is: projects.gleesik.ro (This can be just www.example.com)
# My folder for Demo Website is: /sera-onepage so baseurl: /sera-onepage
#
baseurl:

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: hallo@wien.coderdojo.net

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: '/#contact'

####################################
######  Global Social Links   ######
####################################
youtube: 'https://www.youtube.com/channel/UCsNUvEMrAXmWUicpXJXHKQw'
pinterest:
facebook: 'https://www.facebook.com/coderdojowien'
twitter: 'https://twitter.com/coderdojowien'
google-plus: 'https://plus.google.com/b/117361304524937577544/117361304524937577544/'
vimeo:
linkedin: 'https://www.linkedin.com/company/coderdojowien'

# Google Map JS api
# This is my api for this template
key-api: AIzaSyA3sRKRuJN5RybRwAc79U3wBn6S8SEfVU4
map-text: CoderDojo Wien
map-text-location: Vienna, Austria
map-lat: 48.2108226
map-lng: 16.3675638

#####################################
#############   About   #############
#####################################
about-title: CoderDojo Wien
about-description: "Das CoderDojo ist ein Club für Kinder und Jugendliche zwischen 8 und 17 Jahren, in dem sie Technik und Programmieren lernen können. In regelmäßigen Treffen werden verschiedene Übungen gemacht.
<h2>Für wen</h2>
<p>Wenn du zwischen 8 und 17 Jahre alt bist, komm vorbei. Alles was du machen musst, ist sich <a href=\"#events\">für einen Termin anzumelden.</a>
Wenn du jünger als 13 Jahre bist, muss dich ein Erwachsener begleiten und ganze Zeit anwesend sein.</p>
<h2>Was du mitnehmen solltest</h2>
<p>Du brauchst einen Laptop, es ist aber egal ob Windows, MacOS oder Linux. Ein Tablet oder Smartphone reicht nicht aus, egal ob iPad oder Android.</p>
<h2>Wie läuft ein CoderDojo ab</h2>
<p>Dōjō [doːdʑoː] kommt aus japanischen und steht für einen Trainingsraum für verschiedene Kampfkünste. Wir werden gemeinsam jedoch keine Kampfkünste sondern Programmieren tranieren. 
Wir haben einige Beispiele vorbereitet, jedoch stehen deine Ideen im Mittelpunkt. Wenn du ein cooles Projekt hast, bring es mit. Im CoderDojo 
hast du Hilfe von <a href=\"#team\">Mentoren</a>, die viel Erfahrung und Wissen haben. Ein Mentor begleitet dich bei den ersten Schritten aber auch wenn du 
schon erfahrener bist und eigene Projekte umsetzen möchtest.</p>"

#####################################
############  Exercises  ############
#####################################
exercises-title: Übungen
exercises-description:

#####################################
############### Team ################
#####################################
team-title: Unser Team
team-description: "Wir sind ehrenamtlich engagierte Fachexperten. Wir kommen um dich zu unterstützen und in dir das Potenzial zu entfalten. 
Aber wir lernen und hören auch gerne zu. Wir sind keine Lehrer, sondern Menschen die Spaß daran haben mit Kindern zu arbeiten.
<h2>Mentor werden</h2>
<p>Möchtest du selber ein Mentor werden? Fülle unsere <a href=\"https://de.surveymonkey.com/r/GBNGGFP\">Umfrage</a> aus oder <a href=\"#contact\">schreib uns.</a></p>"

# Members in separate data file

#####################################
############## Events ###############
#####################################
events-title: Termine
events-description:

#####################################
############   Contact   ############
#####################################
contact-title: Sag Hallo
contact-description: Hast du Fragen oder Anregungen? Schreib uns hier oder sag einfach <a href="mailto:hallo@wien.coderdojo.net">Hallo</a>!

#####################################
#############   Footer   ############
#####################################
footer-description:
footer-copyright-text: CoderDojo Wien
footer-copyright-url:
footer-copyright-year: 2017
footer-imprint-text: Impressum und Datenschutz
footer-imprint-url: /impressum

#####################################
############# Components ############
#####################################
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-assets
  - jekyll-last-modified-at

sass:
  sass_dir: _scss
  style: compressed

# Information for compile
exclude: [".gitignore", "node_modules", "docker-compose.yml", "Gemfile", "Gemfile.lock", "gulpfile.js", "package.json", "README.md"]