#
# Sera - OnePage Jekyll Template
# Configuration File
#

# Information for compile
exclude: [".gitignore", "node_modules", "docker-compose.yml", "Gemfile", "Gemfile.lock", "gulpfile.js", "package.json", "README.md"]

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: CoderDojo Wien
# Website language
lang: de-AT
# Header Title
header-title: <strong>bald</strong> da
# Header Tagline
headter-tagline: Wir sind

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Termine
  url: '#events'

# Secondary Buttons
header-secondary-button:
  title: Übungen
  url: '#exercises'

#
# If your website is placed in a separate folder on your server please modify
# this with your folder name, by default is empty.
# Example: Sera Demo is hosted on projects.gleesik.ro/sera-onepage
# If I compile Sera Template and I put in /sera-onepage without modifing baseurl
# than scripts can't be loaded corectly.
# For this example my site url is: projects.gleesik.ro (This can be just www.example.com)
# My folder for Demo Website is: /sera-onepage so baseurl: /sera-onepage
#
baseurl: 

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: hallo@wien.coderdojo.net

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: '#contact'

####################################
######  Global Social Links   ######
####################################
youtube: '#'
pinterest: '#'
facebook: 'https://www.facebook.com/coderdojowien'
twitter: 'https://twitter.com/coderdojowien'
google-plus: '#'
vimeo: '#'

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: avatar-02.jpg
  author-name: John Doe
  author-tagline: Blog Author
  author-info: Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies nec.
  author-social-links:
    youtube: '#'
    pinterest: '#'
    facebook: '#'
    twitter: '#'
    google-plus: '#'

# Google Map JS api
# This is my api for this template
key-api: AIzaSyA3sRKRuJN5RybRwAc79U3wBn6S8SEfVU4
map-text: CoderDojo Wien
map-text-location: Vienna, Austria
map-lat: 48.2108226
map-lng: 16.3675638

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: REPLACEME
  list-id: REPLACEME

####
#
# Hi you now use Sera - OnePage Jekyll Template created by Gleesik™
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
about-title: CoderDojo Wien
about-description: Das CoderDojo ist ein Club für Kinder und Jugendliche, die programmieren lernen und Spaß haben wollen. In regelmäßigen Treffen wird gelernt wie man Code schreibt, Webseiten entwickelt oder Apps und Spiele programmiert.


#####################################
#############  Features  ############
#####################################
features-title: Features
features-description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante.

#
# Features
#
features:

# Feature
- title: Clean & Unique Design
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-vector

# Feature
- title: Professional Support
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-help2

# Feature
- title: Pixel Perfect
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-airplay


#####################################
############  Exercises  ############
#####################################
exercises-title: Übungen
exercises-description: Maecenas tempus nec mi et placerat. Duis at odio vitae ex gravida volutpat. Nulla finibus aliquet diam ut eleifend. Mauris consequat interdum quam. Mauris dui sapien, efficitur et cursus id, molestie fringilla turpis.

#####################################
##########  Core Features  ##########
#####################################
core-title: Core Features
core-description: Duis at odio vitae ex gravida volutpat. Nulla finibus aliquet diam ut eleifend. Mauris consequat interdum quam. Mauris dui sapien, efficitur et cursus id, molestie fringilla turpis aliquet diam ut eleifend.

#
# Core Features Left
#
core-features-left:

# Feature
- name: Creative
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-light

# Feature
- name: Minimalism
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-drop

# Feature
- name: Clean Coding
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-coffee

# Feature
- name: Friendly
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-smile

#
# Core Features Right
#
core-features-right:

# Feature
- name: Branding
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-wine

# Feature
- name: Web Design
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-monitor

# Feature
- name: Graphic Design
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-crop

# Feature
- name: Photography
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-camera

#####################################
############### Team ################
#####################################
team-title: Unser Team
team-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

# Members in separate data file

#####################################
############## Events ###############
#####################################
events-title: Termine
events-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

#
# Plan Personal
#
plan-personal-price: $99
plan-personal-offer-1-title: 01 PSD Pack
plan-personal-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-personal-offer-2-title: 100 Support Tickets
plan-personal-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-personal-url: '#'

#
# Plan Business
#
plan-business-price: $499
plan-business-offer-1-title: 05 PSD Pack
plan-business-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-business-offer-2-title: 1000 Support Tickets
plan-business-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-business-url: '#'

#
# Plan Ultimate
#
plan-ultimate-price: $999
plan-ultimate-offer-1-title: 10 PSD Pack
plan-ultimate-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-ultimate-offer-2-title: Support Unlimited
plan-ultimate-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-ultimate-url: '#'


#####################################
############   Contact   ############
#####################################
contact-title: Sagen sie Hallo
contact-description: Bei Fragen oder Anregungen schreiben sie uns hier oder sagens sie einfach <a href="mailto:hallo@wien.coderdojo.net">Hallo</a>!


#####################################
#############   Footer   ############
#####################################
footer-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat.
footer-copyright-text: CoderDojo Wien
footer-copyright-url: '#'
footer-copyright-year: 2017

#####################################
############# Components ############
#####################################
gems:
  - jekyll-sitemap

sass:
  sass_dir: _scss
  style: compressed